name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    name: "Spellcheck"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade codespell
      - name: Run spellcheck
        run: |
          codespell $(git ls-files 'index.html' 'html/*.html')
  tidy:
    runs-on: ubuntu-latest
    name: "Tidy"
    steps:
      - uses: actions/checkout@v4
      - name: Install HTML Tidy
        run: |
          sudo apt-get install tidy
      - name: Run lint
        run: |
          ./lint.sh
